//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGram.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Complaint
    {
        public int Complaint_Number { get; set; }
        public string Raised_By { get; set; }
        public string RaisedByUniqueID { get; set; }
        public string AgainstParty { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string CreatedOn { get; set; }
        public string Status { get; set; }
        public string Reviewbycomitee { get; set; }
        public Nullable<int> Meeting { get; set; }
        public string FileName { get; set; }
        public HttpPostedFile ImageFile { get; set; }
    }
}
