//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboardobj
    {
        public int Guid { get; set; }
        public Nullable<bool> Isaresident { get; set; }
        public Nullable<bool> Isaplace { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FilePath { get; set; }
        public string ImageName { get; set; }
        public byte[] Image { get; set; }
    }
}
