//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schema
    {
        public int SchemeID { get; set; }
        public string SchemaName { get; set; }
        public string Description { get; set; }
        public string Condition { get; set; }
        public string URL { get; set; }
        public Nullable<int> Village { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ActiveTill { get; set; }
        public string Status { get; set; }
        public string ImagePath { get; set; }
        public string FileName { get; set; }
    }
}
